### ISSUE TITLE
Issue on show()

### ISSUE THREAD

**Issue by jehad-suliman** [Agraphie/MaterialSearchView#2]
```
FATAL EXCEPTION: main
    Process: com.xxx.www.xxx, 
    java.lang.StackOverflowError: stack size 8MB
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7747)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
2019-06-30 11:43:13.387 29661-29661/com.xxx.www.xxx E/AndroidRuntime:     at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:7749)
```

**Comment by Agraphie** [comment]
This usually happens when you try to attache a view recursively. What does your code look like?
